services:
  - type: web
    name: your-app-name
    env: static
    staticPublishPath: /dist # Replace 'dist' with your build folder
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
